create table if not exists enrollments (
  id bigint generated by default as identity primary key,
  name text not null,
  child_name text not null,
  age integer not null check (age between 2 and 6),
  phone text not null,
  message text,
  created_at timestamptz not null default now()
);

alter table enrollments enable row level security;

create policy "Allow public insert" on enrollments
for insert with check (true);

create policy "Allow public read" on enrollments
for select using (true);
